### ISSUE TITLE
routing

### ISSUE THREAD

**Issue by Cholgrrr** [Cholgrrr/nasaproject#10]
Improve on the current Methode of Routing by allowing it to avoid the blooming trees if necessary and selected.

- [x] The search for location doesnt work anymore (probably because of the new API Key regulations of Google)

- [x] The autocorrect function is also disabled

**Comment by Thunyathep** [comment]
The route generated by Waypoint from Google not attach to the road.
Our hope is @giulianobaumann to use his cool routing 👯‍♂️
